services:
  backend:
    build: ./backend
    container_name: mern_blog_backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    networks:
      - blog_network

  frontend:
    build: ./frontend
    container_name: mern_blog_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - blog_network

  agent-service:
    build: ../blog_agent_service
    container_name: mern_blog_agent
    environment:
      - WEB_APP_URL=http://backend:5000/api/blogs/agent
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ../blog_agent_service/.env
    networks:
      - blog_network

networks:
  blog_network:
    driver: bridge
